dialogStyle = ("background-color: rgb(24, 30, 54)\n""")

ipLabelStyle = ("QLabel{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    margin-left: -200px;    \n"
"}\n"
"")

ipInputStyle = ("QLineEdit{\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    border: 2px solid;\n"
"    border-color: #2E3349;\n"
"    border-radius: 8px;\n"
"    background: #252A40;\n"
"}\n"
"\n"
"")

portLabelStyle = ("QLabel{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}")

portInputStyle = ("QLineEdit{\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    border: 2px solid;\n"
"    border-color: #2E3349;\n"
"    border-radius: 8px;\n"
"    background: #252A40;\n"
"}\n"
"")

nickLabelStyle = ("QLabel{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    margin-left: -200px;    \n"
"}\n"
"")

nickInputLabel = ("QLineEdit{\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    border: 2px solid;\n"
"    border-color: #2E3349;\n"
"    border-radius: 8px;\n"
"    background: #252A40;\n"
"}\n"
"\n"
"")

startBtnStartStyle = ("QPushButton\n"
"{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    background-color: #007f5f;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    border: 5px solid #2b9348;\n"
"    letter-spacing: 2px;\n"
"    outline: none; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #2b9348;\n"
"    border: 5px solid #007f5f;\n"
"}\n""")

startBtnStopStyle = ("QPushButton\n"
"{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    letter-spacing: 1px;\n"
"    background-color: #a01a58;\n"
"    border: 5px solid #b7094c;\n"
"    outline: none; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #b7094c;\n"
"    border: 5px solid #a01a58;\n"
"}\n""")

statusBarStyle = ("QLineEdit{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    padding-left: 10px;\n"
"    background-color: #252A40;\n"
"    border: 5px solid #2E3349;\n"
"    color: white;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"     selection-background-color: #2E334;\n"
"}")

spkBtnStyle = ("QPushButton\n"
"{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    background-color: #252A40;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    border: 5px solid #2E3349;\n"
"    letter-spacing: 2px;\n"
"    outline: none; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #2E3349;\n"
"    border: 5px solid #252A40;\n"
"}\n"
"\n"
"\n"
"")

micBtnStyle = ("QPushButton\n"
"{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    background-color: #252A40;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    border: 5px solid #2E3349;\n"
"    letter-spacing: 2px;\n"
"    outline: none; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #2E3349;\n"
"    border: 5px solid #252A40;\n"
"}\n"
"\n"
"\n"
"")