# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(600, 799)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setStyleSheet("background-color: rgb(24, 30, 54)\n"
"")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 781))
        self.layoutWidget.setObjectName("layoutWidget")
        self.contentLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.contentLayout.setContentsMargins(0, 0, 0, 0)
        self.contentLayout.setObjectName("contentLayout")
        self.roomsDropDown = QtWidgets.QComboBox(self.layoutWidget)
        self.roomsDropDown.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.roomsDropDown.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.roomsDropDown.setStyleSheet("QComboBox{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    padding-left: 10px;\n"
"    background-color: #252A40;\n"
"    border: 5px solid #2E3349;\n"
"    color: white;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"     selection-background-color: #2E334;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    color: white;\n"
"    background-color: #252A40;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"   image: url(:/images/dropdown.png);\n"
"   width: 14px;\n"
"   height: 14px;\n"
"   padding-right: 10px;\n"
"   border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"     image: url(:/images/dropdown_on.png);\n"
"}\n"
"QListView{\n"
"  margin-top: 10px;\n"
"  color: #fff;\n"
"  border: 5px solid #2E3349;\n"
"  radius: 8px;\n"
"  border-radius: 8px;\n"
"  selection-color: white;\n"
"  selection-background-color: #2E3349;\n"
"  outline: none;\n"
"  \n"
"}\n"
"\n"
"\n"
"")
        self.roomsDropDown.setEditable(False)
        self.roomsDropDown.setObjectName("roomsDropDown")
        self.roomsDropDown.addItem("")
        self.roomsDropDown.addItem("")
        self.roomsDropDown.addItem("")
        self.contentLayout.addWidget(self.roomsDropDown)
        self.logsArea = QtWidgets.QTextBrowser(self.layoutWidget)
        self.logsArea.setStyleSheet("QTextBrowser#logsArea\n"
"{\n"
"    background-color: #252A40;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    border: 5px solid #2E3349;\n"
"}\n"
"\n"
"")
        self.logsArea.setObjectName("logsArea")
        self.contentLayout.addWidget(self.logsArea)
        self.bottomLayout = QtWidgets.QFormLayout()
        self.bottomLayout.setObjectName("bottomLayout")
        self.inputsLayout = QtWidgets.QGridLayout()
        self.inputsLayout.setObjectName("inputsLayout")
        self.ipLayout = QtWidgets.QFormLayout()
        self.ipLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.ipLayout.setObjectName("ipLayout")
        self.ipLabel = QtWidgets.QLabel(self.layoutWidget)
        self.ipLabel.setMinimumSize(QtCore.QSize(40, 20))
        self.ipLabel.setMaximumSize(QtCore.QSize(40, 20))
        self.ipLabel.setStyleSheet("QLabel{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    margin-left: -200px;    \n"
"}\n"
"")
        self.ipLabel.setObjectName("ipLabel")
        self.ipLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ipLabel)
        self.ipInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.ipInput.setMinimumSize(QtCore.QSize(150, 20))
        self.ipInput.setMaximumSize(QtCore.QSize(150, 20))
        self.ipInput.setToolTip("")
        self.ipInput.setStyleSheet("QLineEdit{\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    border: 2px solid;\n"
"    border-color: #2E3349;\n"
"    border-radius: 8px;\n"
"    background: #252A40;\n"
"}\n"
"\n"
"")
        self.ipInput.setObjectName("ipInput")
        self.ipLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ipInput)
        self.inputsLayout.addLayout(self.ipLayout, 0, 0, 1, 1)
        self.portLayout = QtWidgets.QFormLayout()
        self.portLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.portLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.portLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.portLayout.setObjectName("portLayout")
        self.portLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLabel.sizePolicy().hasHeightForWidth())
        self.portLabel.setSizePolicy(sizePolicy)
        self.portLabel.setMinimumSize(QtCore.QSize(40, 20))
        self.portLabel.setMaximumSize(QtCore.QSize(40, 20))
        self.portLabel.setStyleSheet("QLabel{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"}")
        self.portLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.portLabel.setOpenExternalLinks(False)
        self.portLabel.setObjectName("portLabel")
        self.portLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.portLabel)
        self.portInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.portInput.setMinimumSize(QtCore.QSize(150, 20))
        self.portInput.setMaximumSize(QtCore.QSize(150, 20))
        self.portInput.setStyleSheet("QLineEdit{\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    border: 2px solid;\n"
"    border-color: #2E3349;\n"
"    border-radius: 8px;\n"
"    background: #252A40;\n"
"}\n"
"")
        self.portInput.setObjectName("portInput")
        self.portLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.portInput)
        self.inputsLayout.addLayout(self.portLayout, 1, 0, 1, 1)
        self.bottomLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.inputsLayout)
        self.btnLayout = QtWidgets.QGridLayout()
        self.btnLayout.setObjectName("btnLayout")
        self.startBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.startBtn.setMinimumSize(QtCore.QSize(100, 30))
        self.startBtn.setMaximumSize(QtCore.QSize(100, 30))
        self.startBtn.setStyleSheet("QPushButton\n"
"{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #fff;\n"
"    font-size: 14px;\n"
"    background-color: #252A40;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    border: 5px solid #2E3349;\n"
"    letter-spacing: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #2E3349;\n"
"    border: 5px solid #252A40;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.startBtn.setObjectName("startBtn")
        self.btnLayout.addWidget(self.startBtn, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bottomLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.btnLayout)
        self.contentLayout.addLayout(self.bottomLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.roomsDropDown.setItemText(0, _translate("Dialog", "ROOM_1 - IP 192.168.0.1 - PORT - 66003"))
        self.roomsDropDown.setItemText(1, _translate("Dialog", "2"))
        self.roomsDropDown.setItemText(2, _translate("Dialog", "3"))
        self.ipLabel.setText(_translate("Dialog", "IP:"))
        self.portLabel.setText(_translate("Dialog", "Port:"))
        self.startBtn.setText(_translate("Dialog", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
